### ISSUE TITLE
n^2 performance with javafx

### ISSUE THREAD

**Issue by DuaneTiemann** [jfree/jsfreechart#11]
I'm using javafx from JFreeChart. I notice that plotting 2M points took 4m while 4M points took 83m.  That is due to JFreeChart's drawFirstPassShape and drawSecondaryPass use of setPaint() for each item.  setPaint calls writePaint which adds to a GrowableDataBuffer which expands incrementally.  That results in n^2 performance. Maybe javafx providing a better hint or allowing clients to provide a hint... I hacked a hint into javafx's Canvas.getBuffer. That reduced the time to 30s.

Cross posted to javafx. I expect it is more of a javafx issue, but wanted to provide a heads up...

jfreechart 1.0.19  javafx 1.8.0_45

Duane Tiemann

**Comment by jfree** [comment]
This looks like an issue with FXGraphics2D...I'll close this bug and reopen it over there:

https://github.com/jfree/fxgraphics2d/issues/2
